### ISSUE TITLE
LibDisguises bug

### ISSUE THREAD

**Issue by Keopsfenks** [aematsubara/RealisticVillagers#3]
java.lang.NoSuchMethodError: 'net.minecraft.world.entity.npc.VillagerData me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.fV()'
	at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.getProfession(VillagerNPC.java:1132) ~[RealisticVillagers-1.1.2.jar:?]
	at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.registerBrainGoals(VillagerNPC.java:265) ~[RealisticVillagers-1.1.2.jar:?]
	at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.a(VillagerNPC.java:245) ~[RealisticVillagers-1.1.2.jar:?]
	at net.minecraft.world.entity.LivingEntity.<init>(LivingEntity.java:304) ~[?:?]
	at net.minecraft.world.entity.Mob.<init>(Mob.java:139) ~[?:?]
	at net.minecraft.world.entity.PathfinderMob.<init>(PathfinderMob.java:18) ~[?:?]
	at net.minecraft.world.entity.AgeableMob.<init>(AgeableMob.java:25) ~[?:?]
	at net.minecraft.world.entity.npc.AbstractVillager.<init>(AbstractVillager.java:65) ~[?:?]
	at net.minecraft.world.entity.npc.Villager.<init>(Villager.java:148) ~[?:?]
	at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.<init>(VillagerNPC.java:232) ~[RealisticVillagers-1.1.2.jar:?]
	at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.<init>(VillagerNPC.java:228) ~[RealisticVillagers-1.1.2.jar:?]
	at me.matsubara.realisticvillagers.nms.v1_19_r1.NMSConverter.lambda$registerEntity$0(NMSConverter.java:87) ~[RealisticVillagers-1.1.2.jar:?]
	at net.minecraft.world.entity.EntityType.create(EntityType.java:512) ~[?:?]
	at me.libraryaddict.disguise.utilities.reflection.v1_19_1.ReflectionManager.createEntityInstance(ReflectionManager.java:147) ~[LibsDisguises-10.0.31-Free.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.v1_19_1.ReflectionManager.createEntityInstance(ReflectionManager.java:92) ~[LibsDisguises-10.0.31-Free.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createEntityInstance(ReflectionManager.java:532) ~[LibsDisguises-10.0.31-Free.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.createNMSValues(ReflectionManager.java:2269) ~[LibsDisguises-10.0.31-Free.jar:?]
	at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.registerValues(ReflectionManager.java:2127) ~[LibsDisguises-10.0.31-Free.jar:?]
	at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:240) ~[LibsDisguises-10.0.31-Free.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]

**Comment by aematsubara** [comment]
LibDisguises doesn't support nms for 1.19.2 yet, there's nothing I can do to fix this because mappings are different per patch version (1.19.{0}, 1.19.{1}, 1.19.{2}), LibDisguises only implements NMS for the first two.

**Comment by Keopsfenks** [comment]
> LibDisguises doesn't support nms for 1.19.2 yet, there's nothing I can do to fix this because mappings are different per patch version (1.19.{0}, 1.19.{1}, 1.19.{2}), LibDisguises only implements NMS for the first two.

thanks i understand

**Comment by libraryaddict** [comment]
I'm sorry but this looks like a bug in RealisticVillagers.

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.npc.VillagerData me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.fV()'
at me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC.getProfession(VillagerNPC.java:1132) ~[RealisticVillagers-1.1.2.jar:?]

LD tried to get VillagerData or something maybe, but your class is trying to access a method that doesn't exist.

**Comment by aematsubara** [comment]
Well, I've tested adding both plugins and got only one error about MetaIndex, but other than that, it's working fine.

`[ERROR] .... [LibsDisguises] MetaIndex not found for VILLAGER! Index: 19`
`[ERROR] .... [LibsDisguises] Value: false (class java.lang.Boolean) (class me.matsubara.realisticvillagers.entity.v1_19_r1.VillagerNPC) & VillagerWatcher`

[libraryaddict](https://github.com/libraryaddict) Sorry to bother you, but do you know what's causing this? Both plugins works fine, just that error.

[Keopsfenks](https://github.com/Keopsfenks) you're using paper-138, the latest release is 177, maybe an update can fix this; other than that, I don't know what could be causing this. I'll do more digging if still doesn't work.

**Comment by libraryaddict** [comment]
Try looking at the final jar output, maybe you're not remapping stuff properly on compilation. Not sure.

**Comment by aematsubara** [comment]
Working good with latest paper + latest RealisticVillagers, create a new issue if this happen again
