### ISSUE TITLE
paper 1.21.1 #15 when open combat->player->"ERROR"

### ISSUE THREAD

**Issue by chen17-yixuan** [aematsubara/RealisticVillagers#45]
`[19:10:22 ERROR]: Could not pass event InventoryClickEvent to RealisticVillagers v3.3.3 
java.lang.NoSuchMethodError: 'org.bukkit.craftbukkit.inventory.CraftInventoryView me.matsubara.realisticvillagers.util.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitView()'
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.util.anvilgui.version.Wrapper1_21_R1$AnvilContainer.getBukkitInventory(Wrapper1_21_R1.java:149) ~[RealisticVillagers-3.3.3.jar:?]
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.util.anvilgui.AnvilGUI.openInventory(AnvilGUI.java:212) ~[RealisticVillagers-3.3.3.jar:?]
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.util.anvilgui.AnvilGUI.access$1000(AnvilGUI.java:38) ~[RealisticVillagers-3.3.3.jar:?]
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.util.anvilgui.AnvilGUI$Builder.open(AnvilGUI.java:712) ~[RealisticVillagers-3.3.3.jar:?]
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.listener.InventoryListeners.openAddNewPlayerGUI(InventoryListeners.java:590) ~[RealisticVillagers-3.3.3.jar:?]
        at RealisticVillagers-3.3.3.jar/me.matsubara.realisticvillagers.listener.InventoryListeners.onInventoryClick(InventoryListeners.java:363) ~[RealisticVillagers-3.3.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor40.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-15-11b4ac7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3117) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1466) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1473) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1318) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-15-11b4ac7]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]`

![屏幕截图 2024-08-15 191347](https://github.com/user-attachments/assets/a35022b4-5eba-4f42-88d1-df59162e4083)

**and when I change "config.yml" animals value has some problem**
change two words name is not useful,for example 
![屏幕截图 2024-08-15 191827](https://github.com/user-attachments/assets/bd77b7b2-9c3b-41f9-a414-6a6e2a695ff1)
single word is useful
![image](https://github.com/user-attachments/assets/794b20c9-9305-48b5-980e-17df3c60f239)

thanks for your plugin. I like your plugin. 
![05227A49](https://github.com/user-attachments/assets/951499e2-a3c5-47f8-b732-e7369384bb80)

I am sorry for my english is not good.
spigot:[slv198](https://www.spigotmc.org/members/slv198.1376012/)

**Comment by aematsubara** [comment]
Hi, since you're using 1.21.1 you need to use the latest RealisticVillagers version (3.3.3.1)

For the other issue, try adding -Dfile.encoding=UTF-8 to you start.bat file
