### ISSUE TITLE
NoSuchElementExceptions in server log

### ISSUE THREAD

**Issue by marcelschoen** [aematsubara/RealisticVillagers#7]
Seems I was a bit too quick to say there are no exceptions anymore. For some reason, when I immediately tested your snapshot, there weren't. But I did not delete and re-create my world there - maybe that was my error. I have now deleted the world, and it's regenerating, and I see these kinds of exceptions in the log:

```
deadlyrealms    | [14:10:56 ERROR]: Could not pass event EntityAddToWorldEvent to RealisticVillagers v1.2.2
deadlyrealms    | java.util.NoSuchElementException: No value present
deadlyrealms    | 	at java.util.Optional.get(Unknown Source) ~[?:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.getTextures(VillagerTracker.java:468) ~[RealisticVillagers-1.2.2.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.tracker.VillagerTracker.spawnNPC(VillagerTracker.java:421) ~[RealisticVillagers-1.2.2.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.listener.spawn.BukkitSpawnListeners.handleSpawn(BukkitSpawnListeners.java:80) ~[RealisticVillagers-1.2.2.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.listener.spawn.BukkitSpawnListeners.handleSpawn(BukkitSpawnListeners.java:63) ~[RealisticVillagers-1.2.2.jar:?]
deadlyrealms    | 	at me.matsubara.realisticvillagers.listener.spawn.PaperSpawnListeners.execute(PaperSpawnListeners.java:50) ~[RealisticVillagers-1.2.2.jar:?]
deadlyrealms    | 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
deadlyrealms    | 	at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingStart(ServerLevel.java:2588) ~[?:?]
deadlyrealms    | 	at net.minecraft.server.level.ServerLevel$EntityCallbacks.c(ServerLevel.java:2517) ~[?:?]
deadlyrealms    | 	at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:265) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.world.ChunkEntitySlices.updateStatus(ChunkEntitySlices.java:194) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.entity.EntityLookup.chunkStatusChange(EntityLookup.java:304) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.changeEntityChunkStatus(NewChunkHolder.java:1240) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1309) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1036) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1020) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:905) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleTickingState(ChunkTaskScheduler.java:293) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.scheduleChunkLoad(ChunkTaskScheduler.java:399) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.level.ServerChunkCache.getChunkFutureMainThread(ServerChunkCache.java:533) ~[?:?]
deadlyrealms    | 	at net.minecraft.server.level.ServerChunkCache.getChunk(ServerChunkCache.java:440) ~[?:?]
deadlyrealms    | 	at net.minecraft.world.level.Level.getChunk(Level.java:502) ~[?:?]
deadlyrealms    | 	at net.minecraft.world.level.Level.getChunk(Level.java:442) ~[?:?]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getHighestBlockYAt(CraftWorld.java:983) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:993) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.CraftWorld.getHighestBlockAt(CraftWorld.java:998) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at com.ryandw11.structure.structure.properties.StructureYSpawning.getHighestBlock(StructureYSpawning.java:120) ~[CustomStructures-1.8.2-custom-SNAPSHOT.jar:?]
deadlyrealms    | 	at com.ryandw11.structure.utils.StructurePicker.run(StructurePicker.java:72) ~[CustomStructures-1.8.2-custom-SNAPSHOT.jar:?]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
deadlyrealms    | 	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
It is probably still somehow related to the "CustomStructures" plugin that I also use. Also, I see no problems in the game itself; everything seems to work. It's just these exceptions in the log. "CustomStructures" itself uses the "Citizen" NPC plugin to spawn NPCs - so maybe the problem lies in the "Citizen" plugin, really.

**Comment by marcelschoen** [comment]
Hm, it happens when I configure NPCs of type "VILLAGER" in the "CustomStructures" plugin. I guess I can work around this. Not sure what exactly it is that causes it yet.

**Comment by marcelschoen** [comment]
I start to understand one thing - when the "CustomStructures" plugin tries to spawn an NPC of type "VILLAGER", it somehow invokes the "RealisticVillagers" plugin instead of the "Citizen" NPC plugin. 

deadlyrealms    | [14:56:15 INFO]: [CustomStructures] [DEBUG] Set on-click command for NPC: 'quests category hunter'
deadlyrealms    | [14:56:15 ERROR]: Could not pass event CreatureSpawnEvent to RealisticVillagers v1.2.2
deadlyrealms    | java.util.NoSuchElementException: No value present
deadlyrealms    | 	at java.util.Optional.get(Unknown Source) ~[?:?]

I think that there really is a conflict between the "Citizen" NPC plugin and "RealisticVillagers". But I'll have to investigate more.

**Comment by marcelschoen** [comment]
The code in the "CustomStructures" plugin uses this line to spawn an NPC:

        NPC npc = CitizensAPI.getNPCRegistry().createNPC(type, npcName);

Maybe that "getNPCRegistry()" returns something else than it normally does.

**Comment by marcelschoen** [comment]
Ah no... the problem is probably related more to this line of code, that creates a Bukkit event:

            Bukkit.getPluginManager().callEvent(new NPCCreateEvent(npc));

I assume the "RealisticVillager" plugin handles this event, even though it's probably not meant for it.

**Comment by aematsubara** [comment]
Oh, I see... Citizens has its own villager entity (which extends vanilla Villager) so, when my plugin tries to spawn the fake player, its found that it isn't one of my villagers. I can solve this easily but, if you spawn Citizens NPC with type of villager, they'll just look like vanilla villagers. If you want the structure to have RealisticVillagers, using VILLAGER type only (non-NPC) should work.

**Comment by aematsubara** [comment]
Fixed in the latest update, tested myself

**Comment by marcelschoen** [comment]
Yep, works, thanks a lot!!
